name: Deploy Cloud Function

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
      - 'LICENSE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clean unnecessary files
        run: |
          rm -rf .git
          rm -rf .github
          rm .env
          rm .gitignore
          touch .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PASS_KEY=${{ secrets.PASS_KEY }}" >> .env
      - uses: google-github-actions/setup-gcloud@v0
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: authentication
          runtime: nodejs20
#          entry_point: authentication
#          trigger: http
          region: asia-southeast2
          allow_unauthenticated: true

