name: Deploy Cloud Function

on:
  push:
    branches:
      - dev/prisma-integration
    paths-ignore:
      - 'readme.md'
      - 'LICENSE'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clean unnecessary files
        run: |
          rm -rf .git
          rm -rf .github
          rm .env
          rm .gitignore
          touch .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PASS_KEY=${{ secrets.PASS_KEY }}" >> .env
          echo "DATABASE_URL=postgresql://${{ secrets.DB_AUTH_USER }}:${{ secrets.DB_AUTH_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}?schema=${{ secrets.DB_SCHEMA }}&host=${{ secrets.DB_HOST }}" >> .env
      - name: setup package.json for gcp
        run: |
          mv package.json package.json.tmp
          cat package.json.tmp | jq '{ type, dependencies } | { type, dependencies: .dependencies }' > package.json
          rm package.json.tmp

      - uses: google-github-actions/setup-gcloud@v0
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: authentication
          runtime: nodejs20
#          entry_point: authentication
#          trigger: http
          region: asia-southeast2
          allow_unauthenticated: true

